# Generated by Django 6.0.5 on 2026-05-18 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_documentos_clientes_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clientes', verbose_name='Cliente')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.documentos_clientes', verbose_name='Documento Focado')),
            ],
            options={
                'verbose_name': 'Sessão de Interação',
                'verbose_name_plural': 'Sessões de Interação',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Nova (Assistente IA)')], max_length=10, verbose_name='Remetente')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('context_used', models.TextField(blank=True, null=True, verbose_name='Contexto Utilizado (RAG)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='nova.interactionsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Mensagem da Interação',
                'verbose_name_plural': 'Mensagens da Interação',
                'ordering': ['created_at'],
            },
        ),
    ]
