# Generated by Django 6.0.5 on 2026-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_clientes_id_alter_documentos_clientes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_clientes',
            name='arquivo_markdown',
            field=models.FileField(blank=True, null=True, upload_to='documentos/md/%Y/%m/%d', verbose_name='Arquivo Markdown (Docling)'),
        ),
        migrations.AlterField(
            model_name='documentos_clientes',
            name='arquivo',
            field=models.FileField(upload_to='documentos/%Y/%m/%d', verbose_name='Arquivo PDF Original'),
        ),
    ]
