# Generated by Django 6.0.5 on 2026-05-18 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_documentos_clientes_arquivo_markdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_clientes',
            name='arquivo',
            field=models.FileField(upload_to='documentos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls', 'csv', 'docx', 'md'])], verbose_name='Arquivo Original'),
        ),
    ]
