# Generated by Django 6.0.5 on 2026-05-21 13:52

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_documentos_clientes_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_clientes',
            name='content',
            field=martor.models.MartorField(blank=True, null=True, verbose_name='Conteúdo Markdown Extraído'),
        ),
    ]
